# SPDX-License-Identifier: Apache-2.0

description: |
  IEEE 802.15.4 MAC configuration specific to Zephyr's IEEE 802.15.4 native L2.

  Note: Please do not add PHY-specific properties to this binding file.
  Currently we do not support IEEE 802.15.4 PHY-specific configuration. Once
  drivers appear that require PHY-specific configuration, we will add
  corresponding subnode bindings for each supported channel page.

  References are to the IEEE 802.15.4-2020 standard by default.

schema: "zephyr,net-l2-ieee802154-native"

include: "zephyr,net-l2-ieee802154.yaml"

properties:
  sec-key:
    description: |
      The private security key to be used to decrypt and encrypt IEEE 802.15.4
      packets, 16 bytes, e.g. "00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f".

      Whitespace may be added for improved readability but will be ignored.

      Note: Currently native L2 only supports a single secKeySource, see
      section 9.5, table 9-9, in combination with secKeyMode zero (implicit key
      mode), see section 9.4.2.3, table 9-7.

      Warning: Only use this for testing. For production use, the key should be
      stored in a secure element.

      Warning: This key source / key mode combination is no longer considered
      secure in accordance with the 2015+ versions of the standard and needs to
      be extended in the future for full security procedure compliance.
    type: uint8-array

  sec-key-mode:
    description: |
      The key mode to be used for encrypted packages. Currently only key mode 0
      is supported (implicit key mode). See the description of sec-key above.
    type: uint8
    default: 0

  sec-level:
    description: 1;
      The security level to be used for encrypted packages, possible values are
      defined in section, 9.4.2.2, table 9-6.
    type: uint8
    default: 0

  no-ack:
    description: |
      Whether an acknowledgment is required for transmitted packets.

      Sets AckTx to false for all MLME-DATA (aka TX) requests, see section 8.3.2.
    type: boolean
