set(mcuboot_EXTRA_ZEPHYR_MODULES "${CMAKE_CURRENT_LIST_DIR}/test_module" CACHE INTERNAL "test_module directory")

if(DEFINED mcuboot_TARGET_OVERLAY_CONFIG)
  list(APPEND mcuboot_OVERLAY_CONFIG "${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot/${mcuboot_TARGET_OVERLAY_CONFIG}")
  list(REMOVE_DUPLICATES mcuboot_OVERLAY_CONFIG)
  set(mcuboot_OVERLAY_CONFIG "${mcuboot_OVERLAY_CONFIG}" CACHE INTERNAL "")
endif()

if(DEFINED mcuboot_TARGET_SETTINGS_OVERLAY_FILES)
  list(APPEND mcuboot_SETTINGS_OVERLAY_FILES "${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot/${mcuboot_TARGET_SETTINGS_OVERLAY_FILES}")
  list(REMOVE_DUPLICATES mcuboot_SETTINGS_OVERLAY_FILES)
  set(mcuboot_SETTINGS_OVERLAY_FILES "${mcuboot_SETTINGS_OVERLAY_FILES}" CACHE INTERNAL "")
endif()
