# SPDX-License-Identifier: Apache-2.0

description: |
  IPv6 prefix configuration.

  All nodes using this binding SHALL be called "prefixes" and placed inside an
  "ipv6" node.

schema: "zephyr,net-ipv6-prefixes"

child-binding:
  description: |
    Prefix configuration.

    IPv6 prefix nodes SHALL be named like the subnet, they define.

  properties:
    reg:
      type: array
      required: true
      description: prefix identifier

    addr:
      type: string
      required: true
      description: IPv6 prefix, e.g. "2001:db8::".

    len:
      type: int
      default: 64
      description: prefix length (in bits)

    lifetime:
      type: int
      required: true
      description: prefix lifetime in seconds
